
typedef enum
{
    NEXT,
    KEEP = NEXT,
    START,
    CONTENT = START,
    CONTENT_PLUS,
    CONTENT_WHITESPACE,
    CONTENT_CONTINUATION,
    ELEMENT_CDATA_OR_COMMENT,
    ELEMENT_NAME,
    ELEMENT_WITHOUT_CONTENT,
    ELEMENT_CLOSE_NAME,
    ELEMENT_CLOSE_NAME_PLUS,
    ATTRIBUTES_OR_CLOSE,
    ATTRIBUTE_NAME,
    ATTRIBUTE_ASSIGMENT,
    ATTRIBUTE_VALUE_QUOTE,
    ATTRIBUTE_VALUE,
    ATTRIBUTE_VALUE_PLUS,
    ENTITY,
    ENTITY_NAME,
    ENTITY_CODE,
    ENTITY_CODE_PLUS,
    ENTITY_HEXADECIMAL_CODE,
    ENTITY_HEXADECIMAL_CODE_PLUS,
    COMMENT_OR_CDATA,
    CDATA_NAME,
    CDATA_NAME_PLUS,
    CDATA_CONTENT,
    CDATA_CONTENT_PLUS,
    CDATA_CLOSE,
    CDATA_CLOSE_PLUS,
    COMMENT_HYPHEN,
    COMMENT_CONTENT,
    COMMENT_COMMENT_HYPEN,
    COMMENT_CLOSE,
    COMPLETE,
    RETURN,
#ifdef DEBUG
    RESET_RETURN,
#endif
    FAILURE
}
State;


#ifndef DEBUG
#   define RESET_RETURN NEXT
#endif
