
static Cell table[][WRONG] =
{
    /* CONTENT (START) */
    {
        /* WHITESPACE                */ {CONTENT_WHITESPACE, mark_character},
        /* EXCLAMATION             ! */ {CONTENT_PLUS, start_element_substring},
        /* QUOTE                   " */ {CONTENT_PLUS, start_element_substring},
        /* SHARP                   # */ {CONTENT_PLUS, start_element_substring},
        /* AMPERSAND               & */ {ENTITY, NULL, CONTENT_CONTINUATION},
        /* HYPHEN                  - */ {CONTENT_PLUS, start_element_substring},
        /* SLASH                   / */ {CONTENT_PLUS, start_element_substring},
        /* DIGITS                0-9 */ {CONTENT_PLUS, start_element_substring},
        /* SEMICOLON               ; */ {CONTENT_PLUS, start_element_substring},
        /* LESS                    < */ {ELEMENT_CDATA_OR_COMMENT, NULL, CONTENT},
        /* EQUAL                   = */ {CONTENT_PLUS, start_element_substring},
        /* GREATER                 > */ {CONTENT_PLUS, start_element_substring},
        /* HEXADECIMAL DIGITS    A-F */ {CONTENT_PLUS, start_element_substring},
        /* LEFT SQUARE BRACKET     [ */ {CONTENT_PLUS, start_element_substring},
        /* RIGHT SQUARE BRACKET    ] */ {CONTENT_PLUS, start_element_substring},
        /* NAME START CHARACTERS     */ {CONTENT_PLUS, start_element_substring},
        /* X                       X */ {CONTENT_PLUS, start_element_substring},
        /* NAME CHARACTERS           */ {CONTENT_PLUS, start_element_substring},
        /* CHARACTERS                */ {CONTENT_PLUS, start_element_substring},
        /* END                       */ {COMPLETE, complete}
    },
    /* CONTENT_PLUS */
    {
        /* WHITESPACE                */ PASS,
        /* EXCLAMATION             ! */ PASS,
        /* QUOTE                   " */ PASS,
        /* SHARP                   # */ PASS,
        /* AMPERSAND               & */ {ENTITY, end_element_substring, CONTENT_CONTINUATION},
        /* HYPHEN                  - */ PASS,
        /* SLASH                   / */ PASS,
        /* DIGITS                0-9 */ PASS,
        /* SEMICOLON               ; */ PASS,
        /* LESS                    < */ {ELEMENT_CDATA_OR_COMMENT, end_element_substring, CONTENT_CONTINUATION},
        /* EQUAL                   = */ PASS,
        /* GREATER                 > */ PASS,
        /* HEXADECIMAL DIGITS    A-F */ PASS,
        /* LEFT SQUARE BRACKET     [ */ PASS,
        /* RIGHT SQUARE BRACKET    ] */ PASS,
        /* NAME START CHARACTERS     */ PASS,
        /* X                       X */ PASS,
        /* NAME CHARACTERS           */ PASS,
        /* CHARACTERS                */ PASS,
        /* END                       */ ERROR
    },
    /* CONTENT_WHITESPACE */
    {
        /* WHITESPACE                */ PASS,
        /* EXCLAMATION             ! */ {CONTENT_PLUS, start_element_substring_from_mark},
        /* QUOTE                   " */ {CONTENT_PLUS, start_element_substring_from_mark},
        /* SHARP                   # */ {CONTENT_PLUS, start_element_substring_from_mark},
        /* AMPERSAND               & */ {ENTITY, start_element_substring_from_mark_and_end, CONTENT_CONTINUATION},
        /* HYPHEN                  - */ {CONTENT_PLUS, start_element_substring_from_mark},
        /* SLASH                   / */ {CONTENT_PLUS, start_element_substring_from_mark},
        /* DIGITS                0-9 */ {CONTENT_PLUS, start_element_substring_from_mark},
        /* SEMICOLON               ; */ {CONTENT_PLUS, start_element_substring_from_mark},
        /* LESS                    < */ {ELEMENT_CDATA_OR_COMMENT, NULL, CONTENT},
        /* EQUAL                   = */ {CONTENT_PLUS, start_element_substring_from_mark},
        /* GREATER                 > */ {CONTENT_PLUS, start_element_substring_from_mark},
        /* HEXADECIMAL DIGITS    A-F */ {CONTENT_PLUS, start_element_substring_from_mark},
        /* LEFT SQUARE BRACKET     [ */ {CONTENT_PLUS, start_element_substring_from_mark},
        /* RIGHT SQUARE BRACKET    ] */ {CONTENT_PLUS, start_element_substring_from_mark},
        /* NAME START CHARACTERS     */ {CONTENT_PLUS, start_element_substring_from_mark},
        /* X                       X */ {CONTENT_PLUS, start_element_substring_from_mark},
        /* NAME CHARACTERS           */ {CONTENT_PLUS, start_element_substring_from_mark},
        /* CHARACTERS                */ {CONTENT_PLUS, start_element_substring_from_mark},
        /* END                       */ {COMPLETE, complete}
    },
    /* CONTENT_CONTINUATION */
    {
        /* WHITESPACE                */ {CONTENT_PLUS, start_element_substring},
        /* EXCLAMATION             ! */ {CONTENT_PLUS, start_element_substring},
        /* QUOTE                   " */ {CONTENT_PLUS, start_element_substring},
        /* SHARP                   # */ {CONTENT_PLUS, start_element_substring},
        /* AMPERSAND               & */ {ENTITY, NULL, CONTENT_CONTINUATION},
        /* HYPHEN                  - */ {CONTENT_PLUS, start_element_substring},
        /* SLASH                   / */ {CONTENT_PLUS, start_element_substring},
        /* DIGITS                0-9 */ {CONTENT_PLUS, start_element_substring},
        /* SEMICOLON               ; */ {CONTENT_PLUS, start_element_substring},
        /* LESS                    < */ {ELEMENT_CDATA_OR_COMMENT, NULL, CONTENT_CONTINUATION},
        /* EQUAL                   = */ {CONTENT_PLUS, start_element_substring},
        /* GREATER                 > */ {CONTENT_PLUS, start_element_substring},
        /* HEXADECIMAL DIGITS    A-F */ {CONTENT_PLUS, start_element_substring},
        /* LEFT SQUARE BRACKET     [ */ {CONTENT_PLUS, start_element_substring},
        /* RIGHT SQUARE BRACKET    ] */ {CONTENT_PLUS, start_element_substring},
        /* NAME START CHARACTERS     */ {CONTENT_PLUS, start_element_substring},
        /* X                       X */ {CONTENT_PLUS, start_element_substring},
        /* NAME CHARACTERS           */ {CONTENT_PLUS, start_element_substring},
        /* CHARACTERS                */ {CONTENT_PLUS, start_element_substring},
        /* END                       */ {COMPLETE, complete}
    },




    /* ELEMENT_CDATA_OR_COMMENT */
    {
        /* WHITESPACE                */ ERROR,
        /* EXCLAMATION             ! */ {COMMENT_OR_CDATA},
        /* QUOTE                   " */ ERROR,
        /* SHARP                   # */ ERROR,
        /* AMPERSAND               & */ ERROR,
        /* HYPHEN                  - */ ERROR,
        /* SLASH                   / */ {ELEMENT_CLOSE_NAME, NULL, RESET_RETURN},
        /* DIGITS                0-9 */ ERROR,
        /* SEMICOLON               ; */ ERROR,
        /* LESS                    < */ ERROR,
        /* EQUAL                   = */ ERROR,
        /* GREATER                 > */ ERROR,
        /* HEXADECIMAL DIGITS    A-F */ {ELEMENT_NAME, open_element, RESET_RETURN},
        /* LEFT SQUARE BRACKET     [ */ ERROR,
        /* RIGHT SQUARE BRACKET    ] */ ERROR,
        /* NAME START CHARACTERS     */ {ELEMENT_NAME, open_element, RESET_RETURN},
        /* X                       X */ {ELEMENT_NAME, open_element, RESET_RETURN},
        /* NAME CHARACTERS           */ ERROR,
        /* CHARACTERS                */ ERROR,
        /* END                       */ ERROR
    },
    /* ELEMENT_NAME */
    {
        /* WHITESPACE                */ {ATTRIBUTES_OR_CLOSE, close_element_name},
        /* EXCLAMATION             ! */ ERROR,
        /* QUOTE                   " */ ERROR,
        /* SHARP                   # */ ERROR,
        /* AMPERSAND               & */ ERROR,
        /* HYPHEN                  - */ ERROR,
        /* SLASH                   / */ {ELEMENT_WITHOUT_CONTENT, close_element_name},
        /* DIGITS                0-9 */ PASS,
        /* SEMICOLON               ; */ ERROR,
        /* LESS                    < */ ERROR,
        /* EQUAL                   = */ ERROR,
        /* GREATER                 > */ {CONTENT, close_element_name_and_open_content},
        /* HEXADECIMAL DIGITS    A-F */ PASS,
        /* LEFT SQUARE BRACKET     [ */ ERROR,
        /* RIGHT SQUARE BRACKET    ] */ ERROR,
        /* NAME START CHARACTERS     */ PASS,
        /* X                       X */ PASS,
        /* NAME CHARACTERS           */ PASS,
        /* CHARACTERS                */ ERROR,
        /* END                       */ ERROR
    },
    /* ELEMENT_WITHOUT_CONTENT */
    {
        /* WHITESPACE                */ ERROR,
        /* EXCLAMATION             ! */ ERROR,
        /* QUOTE                   " */ ERROR,
        /* SHARP                   # */ ERROR,
        /* AMPERSAND               & */ ERROR,
        /* HYPHEN                  - */ ERROR,
        /* SLASH                   / */ ERROR,
        /* DIGITS                0-9 */ ERROR,
        /* SEMICOLON               ; */ ERROR,
        /* LESS                    < */ ERROR,
        /* EQUAL                   = */ ERROR,
        /* GREATER                 > */ {CONTENT, close_element},
        /* HEXADECIMAL DIGITS    A-F */ ERROR,
        /* LEFT SQUARE BRACKET     [ */ ERROR,
        /* RIGHT SQUARE BRACKET    ] */ ERROR,
        /* NAME START CHARACTERS     */ ERROR,
        /* X                       X */ ERROR,
        /* NAME CHARACTERS           */ ERROR,
        /* CHARACTERS                */ ERROR,
        /* END                       */ ERROR
    },
    /* ELEMENT_CLOSE_NAME */
    {
        /* WHITESPACE                */ ERROR,
        /* EXCLAMATION             ! */ ERROR,
        /* QUOTE                   " */ ERROR,
        /* SHARP                   # */ ERROR,
        /* AMPERSAND               & */ ERROR,
        /* HYPHEN                  - */ ERROR,
        /* SLASH                   / */ ERROR,
        /* DIGITS                0-9 */ ERROR,
        /* SEMICOLON               ; */ ERROR,
        /* LESS                    < */ ERROR,
        /* EQUAL                   = */ ERROR,
        /* GREATER                 > */ ERROR,
        /* HEXADECIMAL DIGITS    A-F */ {ELEMENT_CLOSE_NAME_PLUS, open_element_close_name},
        /* LEFT SQUARE BRACKET     [ */ ERROR,
        /* RIGHT SQUARE BRACKET    ] */ ERROR,
        /* NAME START CHARACTERS     */ {ELEMENT_CLOSE_NAME_PLUS, open_element_close_name},
        /* X                       X */ {ELEMENT_CLOSE_NAME_PLUS, open_element_close_name},
        /* NAME CHARACTERS           */ ERROR,
        /* CHARACTERS                */ ERROR,
        /* END                       */ ERROR
    },
    /* ELEMENT_CLOSE_NAME_PLUS */
    {
        /* WHITESPACE                */ ERROR,
        /* EXCLAMATION             ! */ ERROR,
        /* QUOTE                   " */ ERROR,
        /* SHARP                   # */ ERROR,
        /* AMPERSAND               & */ ERROR,
        /* HYPHEN                  - */ ERROR,
        /* SLASH                   / */ ERROR,
        /* DIGITS                0-9 */ PASS,
        /* SEMICOLON               ; */ ERROR,
        /* LESS                    < */ ERROR,
        /* EQUAL                   = */ ERROR,
        /* GREATER                 > */ {CONTENT, close_element_and_check_name},
        /* HEXADECIMAL DIGITS    A-F */ PASS,
        /* LEFT SQUARE BRACKET     [ */ ERROR,
        /* RIGHT SQUARE BRACKET    ] */ ERROR,
        /* NAME START CHARACTERS     */ PASS,
        /* X                       X */ PASS,
        /* NAME CHARACTERS           */ PASS,
        /* CHARACTERS                */ ERROR,
        /* END                       */ ERROR
    },




    /* ATTRIBUTES_OR_CLOSE */
    {
        /* WHITESPACE                */ PASS,
        /* EXCLAMATION             ! */ ERROR,
        /* QUOTE                   " */ ERROR,
        /* SHARP                   # */ ERROR,
        /* AMPERSAND               & */ ERROR,
        /* HYPHEN                  - */ ERROR,
        /* SLASH                   / */ {ELEMENT_WITHOUT_CONTENT},
        /* SEMICOLON               ; */ ERROR,
        /* DIGITS                0-9 */ ERROR,
        /* LESS                    < */ ERROR,
        /* EQUAL                   = */ ERROR,
        /* GREATER                 > */ {CONTENT, open_element_content},
        /* HEXADECIMAL DIGITS    A-F */ {ATTRIBUTE_NAME, open_attribute},
        /* LEFT SQUARE BRACKET     [ */ ERROR,
        /* RIGHT SQUARE BRACKET    ] */ ERROR,
        /* NAME START CHARACTERS     */ {ATTRIBUTE_NAME, open_attribute},
        /* X                       X */ {ATTRIBUTE_NAME, open_attribute},
        /* NAME CHARACTERS           */ ERROR,
        /* CHARACTERS                */ ERROR,
        /* END                       */ ERROR
    },
    /* ATTRIBUTE_NAME */
    {
        /* WHITESPACE                */ {ATTRIBUTE_ASSIGMENT, close_attribute_name},
        /* EXCLAMATION             ! */ ERROR,
        /* QUOTE                   " */ ERROR,
        /* SHARP                   # */ ERROR,
        /* AMPERSAND               & */ ERROR,
        /* HYPHEN                  - */ ERROR,
        /* SLASH                   / */ ERROR,
        /* DIGITS                0-9 */ PASS,
        /* SEMICOLON               ; */ ERROR,
        /* LESS                    < */ ERROR,
        /* EQUAL                   = */ {ATTRIBUTE_VALUE_QUOTE, close_attribute_name},
        /* GREATER                 > */ ERROR,
        /* HEXADECIMAL DIGITS    A-F */ PASS,
        /* LEFT SQUARE BRACKET     [ */ ERROR,
        /* RIGHT SQUARE BRACKET    ] */ ERROR,
        /* NAME START CHARACTERS     */ PASS,
        /* X                       X */ PASS,
        /* NAME CHARACTERS           */ PASS,
        /* CHARACTERS                */ ERROR,
        /* END                       */ ERROR
    },
    /* ATTRIBUTE_ASSIGMENT */
    {
        /* WHITESPACE                */ PASS,
        /* EXCLAMATION             ! */ ERROR,
        /* QUOTE                   " */ ERROR,
        /* SHARP                   # */ ERROR,
        /* AMPERSAND               & */ ERROR,
        /* HYPHEN                  - */ ERROR,
        /* SLASH                   / */ ERROR,
        /* DIGITS                0-9 */ ERROR,
        /* SEMICOLON               ; */ ERROR,
        /* LESS                    < */ ERROR,
        /* EQUAL                   = */ {ATTRIBUTE_VALUE_QUOTE},
        /* GREATER                 > */ ERROR,
        /* HEXADECIMAL DIGITS    A-F */ ERROR,
        /* LEFT SQUARE BRACKET     [ */ ERROR,
        /* RIGHT SQUARE BRACKET    ] */ ERROR,
        /* NAME START CHARACTERS     */ ERROR,
        /* X                       X */ ERROR,
        /* NAME CHARACTERS           */ ERROR,
        /* CHARACTERS                */ ERROR,
        /* END                       */ ERROR
    },
    /* ATTRIBUTE_VALUE_QUOTE */
    {
        /* WHITESPACE                */ PASS,
        /* EXCLAMATION             ! */ ERROR,
        /* QUOTE                   " */ {ATTRIBUTE_VALUE},
        /* SHARP                   # */ ERROR,
        /* AMPERSAND               & */ ERROR,
        /* HYPHEN                  - */ ERROR,
        /* SLASH                   / */ ERROR,
        /* DIGITS                0-9 */ ERROR,
        /* SEMICOLON               ; */ ERROR,
        /* LESS                    < */ ERROR,
        /* EQUAL                   = */ ERROR,
        /* GREATER                 > */ ERROR,
        /* HEXADECIMAL DIGITS    A-F */ ERROR,
        /* LEFT SQUARE BRACKET     [ */ ERROR,
        /* RIGHT SQUARE BRACKET    ] */ ERROR,
        /* NAME START CHARACTERS     */ ERROR,
        /* X                       X */ ERROR,
        /* NAME CHARACTERS           */ ERROR,
        /* CHARACTERS                */ ERROR,
        /* END                       */ ERROR
    },
    /* ATTRIBUTE_VALUE */
    {
        /* WHITESPACE                */ {ATTRIBUTE_VALUE_PLUS, start_attribute_substring},
        /* EXCLAMATION             ! */ {ATTRIBUTE_VALUE_PLUS, start_attribute_substring},
        /* QUOTE                   " */ {ATTRIBUTES_OR_CLOSE, close_attribute},
        /* SHARP                   # */ {ATTRIBUTE_VALUE_PLUS, start_attribute_substring},
        /* AMPERSAND               & */ {ENTITY, NULL, ATTRIBUTE_VALUE},
        /* HYPHEN                  - */ {ATTRIBUTE_VALUE_PLUS, start_attribute_substring},
        /* SLASH                   / */ {ATTRIBUTE_VALUE_PLUS, start_attribute_substring},
        /* DIGITS                0-9 */ {ATTRIBUTE_VALUE_PLUS, start_attribute_substring},
        /* SEMICOLON               ; */ {ATTRIBUTE_VALUE_PLUS, start_attribute_substring},
        /* LESS                    < */ {ATTRIBUTE_VALUE_PLUS, start_attribute_substring},
        /* EQUAL                   = */ {ATTRIBUTE_VALUE_PLUS, start_attribute_substring},
        /* GREATER                 > */ {ATTRIBUTE_VALUE_PLUS, start_attribute_substring},
        /* HEXADECIMAL DIGITS    A-F */ {ATTRIBUTE_VALUE_PLUS, start_attribute_substring},
        /* LEFT SQUARE BRACKET     [ */ {ATTRIBUTE_VALUE_PLUS, start_attribute_substring},
        /* RIGHT SQUARE BRACKET    ] */ {ATTRIBUTE_VALUE_PLUS, start_attribute_substring},
        /* NAME START CHARACTERS     */ {ATTRIBUTE_VALUE_PLUS, start_attribute_substring},
        /* X                       X */ {ATTRIBUTE_VALUE_PLUS, start_attribute_substring},
        /* NAME CHARACTERS           */ {ATTRIBUTE_VALUE_PLUS, start_attribute_substring},
        /* CHARACTERS                */ {ATTRIBUTE_VALUE_PLUS, start_attribute_substring},
        /* END                       */ {ATTRIBUTE_VALUE_PLUS, start_attribute_substring},
    },
    /* ATTRIBUTE_VALUE_PLUS */
    {
        /* WHITESPACE                */ PASS,
        /* EXCLAMATION             ! */ PASS,
        /* QUOTE                   " */ {ATTRIBUTES_OR_CLOSE, close_attribute_and_end_substring},
        /* SHARP                   # */ PASS,
        /* AMPERSAND               & */ {ENTITY, end_attribute_substring, ATTRIBUTE_VALUE},
        /* HYPHEN                  - */ PASS,
        /* SLASH                   / */ PASS,
        /* DIGITS                0-9 */ PASS,
        /* SEMICOLON               ; */ PASS,
        /* LESS                    < */ ERROR,
        /* EQUAL                   = */ PASS,
        /* GREATER                 > */ PASS,
        /* HEXADECIMAL DIGITS    A-F */ PASS,
        /* LEFT SQUARE BRACKET     [ */ PASS,
        /* RIGHT SQUARE BRACKET    ] */ PASS,
        /* NAME START CHARACTERS     */ PASS,
        /* X                       X */ PASS,
        /* NAME CHARACTERS           */ PASS,
        /* CHARACTERS                */ PASS,
        /* END                       */ ERROR
    },




    /* ENTITY */
    {
        /* WHITESPACE                */ ERROR,
        /* EXCLAMATION             ! */ ERROR,
        /* QUOTE                   " */ ERROR,
        /* SHARP                   # */ {ENTITY_CODE},
        /* AMPERSAND               & */ ERROR,
        /* HYPHEN                  - */ ERROR,
        /* SLASH                   / */ ERROR,
        /* DIGITS                0-9 */ ERROR,
        /* SEMICOLON               ; */ ERROR,
        /* LESS                    < */ ERROR,
        /* EQUAL                   = */ ERROR,
        /* GREATER                 > */ ERROR,
        /* HEXADECIMAL DIGITS    A-F */ {ENTITY_NAME, open_entity_name},
        /* LEFT SQUARE BRACKET     [ */ ERROR,
        /* RIGHT SQUARE BRACKET    ] */ ERROR,
        /* NAME START CHARACTERS     */ {ENTITY_NAME, open_entity_name},
        /* X                       X */ {ENTITY_NAME, open_entity_name},
        /* NAME CHARACTERS           */ ERROR,
        /* CHARACTERS                */ ERROR,
        /* END                       */ ERROR
    },
    /* ENTITY_NAME */
    {
        /* WHITESPACE                */ ERROR,
        /* EXCLAMATION             ! */ ERROR,
        /* QUOTE                   " */ ERROR,
        /* SHARP                   # */ ERROR,
        /* AMPERSAND               & */ ERROR,
        /* HYPHEN                  - */ ERROR,
        /* SLASH                   / */ ERROR,
        /* DIGITS                0-9 */ {KEEP, scan_entity_name},
        /* SEMICOLON               ; */ {RETURN, close_entity_name},
        /* LESS                    < */ ERROR,
        /* EQUAL                   = */ ERROR,
        /* GREATER                 > */ ERROR,
        /* HEXADECIMAL DIGITS    A-F */ {KEEP, scan_entity_name},
        /* LEFT SQUARE BRACKET     [ */ ERROR,
        /* RIGHT SQUARE BRACKET    ] */ ERROR,
        /* NAME START CHARACTERS     */ {KEEP, scan_entity_name},
        /* X                       X */ {KEEP, scan_entity_name},
        /* NAME CHARACTERS           */ {KEEP, scan_entity_name},
        /* CHARACTERS                */ ERROR,
        /* END                       */ ERROR
    },
    /* ENTITY_CODE */
    {
        /* WHITESPACE                */ ERROR,
        /* EXCLAMATION             ! */ ERROR,
        /* QUOTE                   " */ ERROR,
        /* SHARP                   # */ ERROR,
        /* AMPERSAND               & */ ERROR,
        /* HYPHEN                  - */ ERROR,
        /* SLASH                   / */ ERROR,
        /* DIGITS                0-9 */ {ENTITY_CODE_PLUS, open_entity_code},
        /* SEMICOLON               ; */ ERROR,
        /* LESS                    < */ ERROR,
        /* EQUAL                   = */ ERROR,
        /* GREATER                 > */ ERROR,
        /* HEXADECIMAL DIGITS    A-F */ ERROR,
        /* LEFT SQUARE BRACKET     [ */ ERROR,
        /* RIGHT SQUARE BRACKET    ] */ ERROR,
        /* NAME START CHARACTERS     */ ERROR,
        /* X                       X */ {ENTITY_HEXADECIMAL_CODE},
        /* NAME CHARACTERS           */ ERROR,
        /* CHARACTERS                */ ERROR,
        /* END                       */ ERROR
    },
    /* ENTITY_CODE_PLUS */
    {
        /* WHITESPACE                */ ERROR,
        /* EXCLAMATION             ! */ ERROR,
        /* QUOTE                   " */ ERROR,
        /* SHARP                   # */ ERROR,
        /* AMPERSAND               & */ ERROR,
        /* HYPHEN                  - */ ERROR,
        /* SLASH                   / */ ERROR,
        /* DIGITS                0-9 */ {KEEP, scan_entity_code},
        /* SEMICOLON               ; */ {RETURN, close_entity_code},
        /* LESS                    < */ ERROR,
        /* EQUAL                   = */ ERROR,
        /* GREATER                 > */ ERROR,
        /* HEXADECIMAL DIGITS    A-F */ ERROR,
        /* LEFT SQUARE BRACKET     [ */ ERROR,
        /* RIGHT SQUARE BRACKET    ] */ ERROR,
        /* NAME START CHARACTERS     */ ERROR,
        /* X                       X */ ERROR,
        /* NAME CHARACTERS           */ ERROR,
        /* CHARACTERS                */ ERROR,
        /* END                       */ ERROR
    },
    /* ENTITY_HEXADECIMAL_CODE */
    {
        /* WHITESPACE                */ ERROR,
        /* EXCLAMATION             ! */ ERROR,
        /* QUOTE                   " */ ERROR,
        /* SHARP                   # */ ERROR,
        /* AMPERSAND               & */ ERROR,
        /* HYPHEN                  - */ ERROR,
        /* SLASH                   / */ ERROR,
        /* DIGITS                0-9 */ {ENTITY_HEXADECIMAL_CODE_PLUS, open_entity_hexadecimal_code},
        /* SEMICOLON               ; */ ERROR,
        /* LESS                    < */ ERROR,
        /* EQUAL                   = */ ERROR,
        /* GREATER                 > */ ERROR,
        /* HEXADECIMAL DIGITS    A-F */ {ENTITY_HEXADECIMAL_CODE_PLUS, open_entity_hexadecimal_code},
        /* LEFT SQUARE BRACKET     [ */ ERROR,
        /* RIGHT SQUARE BRACKET    ] */ ERROR,
        /* NAME START CHARACTERS     */ ERROR,
        /* X                       X */ ERROR,
        /* NAME CHARACTERS           */ ERROR,
        /* CHARACTERS                */ ERROR,
        /* END                       */ ERROR
    },
    /* ENTITY_HEXADECIMAL_CODE_PLUS */
    {
        /* WHITESPACE                */ ERROR,
        /* EXCLAMATION             ! */ ERROR,
        /* QUOTE                   " */ ERROR,
        /* SHARP                   # */ ERROR,
        /* AMPERSAND               & */ ERROR,
        /* HYPHEN                  - */ ERROR,
        /* SLASH                   / */ ERROR,
        /* DIGITS                0-9 */ {KEEP, scan_entity_hexadecimal_code},
        /* SEMICOLON               ; */ {RETURN, close_entity_code},
        /* LESS                    < */ ERROR,
        /* EQUAL                   = */ ERROR,
        /* GREATER                 > */ ERROR,
        /* HEXADECIMAL DIGITS    A-F */ {KEEP, scan_entity_hexadecimal_code},
        /* LEFT SQUARE BRACKET     [ */ ERROR,
        /* RIGHT SQUARE BRACKET    ] */ ERROR,
        /* NAME START CHARACTERS     */ ERROR,
        /* X                       X */ ERROR,
        /* NAME CHARACTERS           */ ERROR,
        /* CHARACTERS                */ ERROR,
        /* END                       */ ERROR
    },




    /* COMMENT_OR_CDATA */
    {
        /* WHITESPACE                */ ERROR,
        /* EXCLAMATION             ! */ ERROR,
        /* QUOTE                   " */ ERROR,
        /* SHARP                   # */ ERROR,
        /* AMPERSAND               & */ ERROR,
        /* HYPHEN                  - */ {COMMENT_HYPHEN},
        /* SLASH                   / */ ERROR,
        /* DIGITS                0-9 */ ERROR,
        /* SEMICOLON               ; */ ERROR,
        /* LESS                    < */ ERROR,
        /* EQUAL                   = */ ERROR,
        /* GREATER                 > */ ERROR,
        /* HEXADECIMAL DIGITS    A-F */ ERROR,
        /* LEFT SQUARE BRACKET     [ */ {CDATA_NAME, NULL, RESET_RETURN},
        /* RIGHT SQUARE BRACKET    ] */ ERROR,
        /* NAME START CHARACTERS     */ ERROR,
        /* X                       X */ ERROR,
        /* NAME CHARACTERS           */ ERROR,
        /* CHARACTERS                */ ERROR,
        /* END                       */ ERROR
    },
    /* CDATA_NAME */
    {
        /* WHITESPACE                */ ERROR,
        /* EXCLAMATION             ! */ ERROR,
        /* QUOTE                   " */ ERROR,
        /* SHARP                   # */ ERROR,
        /* AMPERSAND               & */ ERROR,
        /* HYPHEN                  - */ ERROR,
        /* SLASH                   / */ ERROR,
        /* DIGITS                0-9 */ ERROR,
        /* SEMICOLON               ; */ ERROR,
        /* LESS                    < */ ERROR,
        /* EQUAL                   = */ ERROR,
        /* GREATER                 > */ ERROR,
        /* HEXADECIMAL DIGITS    A-F */ {CDATA_NAME_PLUS, open_cdata_name},
        /* LEFT SQUARE BRACKET     [ */ ERROR,
        /* RIGHT SQUARE BRACKET    ] */ ERROR,
        /* NAME START CHARACTERS     */ {CDATA_NAME_PLUS, open_cdata_name},
        /* X                       X */ {CDATA_NAME_PLUS, open_cdata_name},
        /* NAME CHARACTERS           */ ERROR,
        /* CHARACTERS                */ ERROR,
        /* END                       */ ERROR
    },
    /* CDATA_NAME_PLUS */
    {
        /* WHITESPACE                */ ERROR,
        /* EXCLAMATION             ! */ ERROR,
        /* QUOTE                   " */ ERROR,
        /* SHARP                   # */ ERROR,
        /* AMPERSAND               & */ ERROR,
        /* HYPHEN                  - */ ERROR,
        /* SLASH                   / */ ERROR,
        /* DIGITS                0-9 */ PASS,
        /* SEMICOLON               ; */ ERROR,
        /* LESS                    < */ ERROR,
        /* EQUAL                   = */ ERROR,
        /* GREATER                 > */ ERROR,
        /* HEXADECIMAL DIGITS    A-F */ PASS,
        /* LEFT SQUARE BRACKET     [ */ {CDATA_CONTENT, close_cdata_name},
        /* RIGHT SQUARE BRACKET    ] */ ERROR,
        /* NAME START CHARACTERS     */ PASS,
        /* X                       X */ PASS,
        /* NAME CHARACTERS           */ PASS,
        /* CHARACTERS                */ ERROR,
        /* END                       */ ERROR
    },
    /* CDATA_CONTENT */
    {
        /* WHITESPACE                */ {CDATA_CONTENT_PLUS, start_cdata_substring},
        /* EXCLAMATION             ! */ {CDATA_CONTENT_PLUS, start_cdata_substring},
        /* QUOTE                   " */ {CDATA_CONTENT_PLUS, start_cdata_substring},
        /* SHARP                   # */ {CDATA_CONTENT_PLUS, start_cdata_substring},
        /* AMPERSAND               & */ {CDATA_CONTENT_PLUS, start_cdata_substring},
        /* HYPHEN                  - */ {CDATA_CONTENT_PLUS, start_cdata_substring},
        /* SLASH                   / */ {CDATA_CONTENT_PLUS, start_cdata_substring},
        /* DIGITS                0-9 */ {CDATA_CONTENT_PLUS, start_cdata_substring},
        /* SEMICOLON               ; */ {CDATA_CONTENT_PLUS, start_cdata_substring},
        /* LESS                    < */ {CDATA_CONTENT_PLUS, start_cdata_substring},
        /* EQUAL                   = */ {CDATA_CONTENT_PLUS, start_cdata_substring},
        /* GREATER                 > */ {CDATA_CONTENT_PLUS, start_cdata_substring},
        /* HEXADECIMAL DIGITS    A-F */ {CDATA_CONTENT_PLUS, start_cdata_substring},
        /* LEFT SQUARE BRACKET     [ */ {CDATA_CONTENT_PLUS, start_cdata_substring},
        /* RIGHT SQUARE BRACKET    ] */ ERROR,
        /* NAME START CHARACTERS     */ {CDATA_CONTENT_PLUS, start_cdata_substring},
        /* X                       X */ {CDATA_CONTENT_PLUS, start_cdata_substring},
        /* NAME CHARACTERS           */ {CDATA_CONTENT_PLUS, start_cdata_substring},
        /* CHARACTERS                */ {CDATA_CONTENT_PLUS, start_cdata_substring},
        /* END                       */ ERROR
    },
    /* CDATA_CONTENT_PLUS */
    {
        /* WHITESPACE                */ PASS,
        /* EXCLAMATION             ! */ PASS,
        /* QUOTE                   " */ PASS,
        /* SHARP                   # */ PASS,
        /* AMPERSAND               & */ PASS,
        /* HYPHEN                  - */ PASS,
        /* SLASH                   / */ PASS,
        /* DIGITS                0-9 */ PASS,
        /* SEMICOLON               ; */ PASS,
        /* LESS                    < */ PASS,
        /* EQUAL                   = */ PASS,
        /* GREATER                 > */ PASS,
        /* HEXADECIMAL DIGITS    A-F */ PASS,
        /* LEFT SQUARE BRACKET     [ */ PASS,
        /* RIGHT SQUARE BRACKET    ] */ {CDATA_CLOSE, mark_character},
        /* NAME START CHARACTERS     */ PASS,
        /* X                       X */ PASS,
        /* NAME CHARACTERS           */ PASS,
        /* CHARACTERS                */ PASS,
        /* END                       */ ERROR
    },
    /* CDATA_CLOSE */
    {
        /* WHITESPACE                */ {CDATA_CONTENT_PLUS},
        /* EXCLAMATION             ! */ {CDATA_CONTENT_PLUS},
        /* QUOTE                   " */ {CDATA_CONTENT_PLUS},
        /* SHARP                   # */ {CDATA_CONTENT_PLUS},
        /* AMPERSAND               & */ {CDATA_CONTENT_PLUS},
        /* HYPHEN                  - */ {CDATA_CONTENT_PLUS},
        /* SLASH                   / */ {CDATA_CONTENT_PLUS},
        /* DIGITS                0-9 */ {CDATA_CONTENT_PLUS},
        /* SEMICOLON               ; */ {CDATA_CONTENT_PLUS},
        /* LESS                    < */ {CDATA_CONTENT_PLUS},
        /* EQUAL                   = */ {CDATA_CONTENT_PLUS},
        /* GREATER                 > */ {CDATA_CONTENT_PLUS},
        /* HEXADECIMAL DIGITS    A-F */ {CDATA_CONTENT_PLUS},
        /* LEFT SQUARE BRACKET     [ */ {CDATA_CONTENT_PLUS},
        /* RIGHT SQUARE BRACKET    ] */ {CDATA_CLOSE_PLUS},
        /* NAME START CHARACTERS     */ {CDATA_CONTENT_PLUS},
        /* X                       X */ {CDATA_CONTENT_PLUS},
        /* NAME CHARACTERS           */ {CDATA_CONTENT_PLUS},
        /* CHARACTERS                */ {CDATA_CONTENT_PLUS},
        /* END                       */ ERROR
    },
    /* CDATA_CLOSE_PLUS */
    {
        /* WHITESPACE                */ {CDATA_CONTENT_PLUS},
        /* EXCLAMATION             ! */ {CDATA_CONTENT_PLUS},
        /* QUOTE                   " */ {CDATA_CONTENT_PLUS},
        /* SHARP                   # */ {CDATA_CONTENT_PLUS},
        /* AMPERSAND               & */ {CDATA_CONTENT_PLUS},
        /* HYPHEN                  - */ {CDATA_CONTENT_PLUS},
        /* SLASH                   / */ {CDATA_CONTENT_PLUS},
        /* DIGITS                0-9 */ {CDATA_CONTENT_PLUS},
        /* SEMICOLON               ; */ {CDATA_CONTENT_PLUS},
        /* LESS                    < */ {CDATA_CONTENT_PLUS},
        /* EQUAL                   = */ {CDATA_CONTENT_PLUS},
        /* GREATER                 > */ {CONTENT_CONTINUATION, end_cdata_substring_to_mark},
        /* HEXADECIMAL DIGITS    A-F */ {CDATA_CONTENT_PLUS},
        /* LEFT SQUARE BRACKET     [ */ {CDATA_CONTENT_PLUS},
        /* RIGHT SQUARE BRACKET    ] */ {CDATA_CONTENT_PLUS},
        /* NAME START CHARACTERS     */ {CDATA_CONTENT_PLUS},
        /* X                       X */ {CDATA_CONTENT_PLUS},
        /* NAME CHARACTERS           */ {CDATA_CONTENT_PLUS},
        /* CHARACTERS                */ {CDATA_CONTENT_PLUS},
        /* END                       */ ERROR
    },



    /* COMMENT_HYPHEN */
    {
        /* WHITESPACE                */ ERROR,
        /* EXCLAMATION             ! */ ERROR,
        /* QUOTE                   " */ ERROR,
        /* SHARP                   # */ ERROR,
        /* AMPERSAND               & */ ERROR,
        /* HYPHEN                  - */ {COMMENT_CONTENT},
        /* SLASH                   / */ ERROR,
        /* DIGITS                0-9 */ ERROR,
        /* SEMICOLON               ; */ ERROR,
        /* LESS                    < */ ERROR,
        /* EQUAL                   = */ ERROR,
        /* GREATER                 > */ ERROR,
        /* HEXADECIMAL DIGITS    A-F */ ERROR,
        /* LEFT SQUARE BRACKET     [ */ ERROR,
        /* RIGHT SQUARE BRACKET    ] */ ERROR,
        /* NAME START CHARACTERS     */ ERROR,
        /* X                       X */ ERROR,
        /* NAME CHARACTERS           */ ERROR,
        /* CHARACTERS                */ ERROR,
        /* END                       */ ERROR
    },
    /* COMMENT_CONTENT */
    {
        /* WHITESPACE                */ PASS,
        /* EXCLAMATION             ! */ PASS,
        /* QUOTE                   " */ PASS,
        /* SHARP                   # */ PASS,
        /* AMPERSAND               & */ PASS,
        /* HYPHEN                  - */ {COMMENT_COMMENT_HYPEN},
        /* SLASH                   / */ PASS,
        /* DIGITS                0-9 */ PASS,
        /* SEMICOLON               ; */ PASS,
        /* LESS                    < */ PASS,
        /* EQUAL                   = */ PASS,
        /* GREATER                 > */ PASS,
        /* HEXADECIMAL DIGITS    A-F */ PASS,
        /* LEFT SQUARE BRACKET     [ */ PASS,
        /* RIGHT SQUARE BRACKET    ] */ PASS,
        /* NAME START CHARACTERS     */ PASS,
        /* X                       X */ PASS,
        /* NAME CHARACTERS           */ PASS,
        /* CHARACTERS                */ PASS,
        /* END                       */ PASS
    },
    /* COMMENT_COMMENT_HYPEN */
    {
        /* WHITESPACE                */ {COMMENT_CONTENT},
        /* EXCLAMATION             ! */ {COMMENT_CONTENT},
        /* QUOTE                   " */ {COMMENT_CONTENT},
        /* SHARP                   # */ {COMMENT_CONTENT},
        /* AMPERSAND               & */ {COMMENT_CONTENT},
        /* HYPHEN                  - */ {COMMENT_CLOSE},
        /* SLASH                   / */ {COMMENT_CONTENT},
        /* DIGITS                0-9 */ {COMMENT_CONTENT},
        /* SEMICOLON               ; */ {COMMENT_CONTENT},
        /* LESS                    < */ {COMMENT_CONTENT},
        /* EQUAL                   = */ {COMMENT_CONTENT},
        /* GREATER                 > */ {COMMENT_CONTENT},
        /* HEXADECIMAL DIGITS    A-F */ {COMMENT_CONTENT},
        /* LEFT SQUARE BRACKET     [ */ {COMMENT_CONTENT},
        /* RIGHT SQUARE BRACKET    ] */ {COMMENT_CONTENT},
        /* NAME START CHARACTERS     */ {COMMENT_CONTENT},
        /* X                       X */ {COMMENT_CONTENT},
        /* NAME CHARACTERS           */ {COMMENT_CONTENT},
        /* CHARACTERS                */ {COMMENT_CONTENT},
        /* END                       */ ERROR
    },
    /* COMMENT_CLOSE */
    {
        /* WHITESPACE                */ ERROR,
        /* EXCLAMATION             ! */ ERROR,
        /* QUOTE                   " */ ERROR,
        /* SHARP                   # */ ERROR,
        /* AMPERSAND               & */ ERROR,
        /* HYPHEN                  - */ ERROR,
        /* SLASH                   / */ ERROR,
        /* DIGITS                0-9 */ ERROR,
        /* SEMICOLON               ; */ ERROR,
        /* LESS                    < */ ERROR,
        /* EQUAL                   = */ ERROR,
        /* GREATER                 > */ {RETURN},
        /* HEXADECIMAL DIGITS    A-F */ ERROR,
        /* LEFT SQUARE BRACKET     [ */ ERROR,
        /* RIGHT SQUARE BRACKET    ] */ ERROR,
        /* NAME START CHARACTERS     */ ERROR,
        /* X                       X */ ERROR,
        /* NAME CHARACTERS           */ ERROR,
        /* CHARACTERS                */ ERROR,
        /* END                       */ ERROR
    }
};
