
# from admin.app import run
# from admin.appbackup import run
# from admin.apprestore import run
# from admin.index import run
# from admin.options import run
# from admin.serverinfo import run
# from admin.config import run
# from admin.date import run
from admin.e2vdom import run
# from admin.echo import run
# from admin.export import run
# from admin.group_new import run
# from admin.grp_modif_grp import run
# from admin.grp_modif_rights_form import run
# from admin.grp_modif_rights import run
# from admin.grp_modif import run
# from admin.grp_suppr import run
# from admin.help import run
# from admin.inithdd import run
# from admin.install import run
# from admin.ip import run
# from admin.log_bug import run
# from admin.log_server import run
# from admin.log_users import run
# from admin.log import run
# from admin.menuappli import run
# from admin.objects_add import run
# from admin.objects_delete import run
# from admin.objects_update import run
# from admin.objects import run
# from admin.reboot import run
# from admin.scrupg import run
# from admin.shutdown import run
# from admin.ssh import run
# from admin.track import run
# from admin.uninstall import run
# from admin.update import run
# from admin.users_ajout import run
# from admin.users_modif_rights_form import run
# from admin.users_modif_rights import run
# from admin.users_modif_user import run
# from admin.users_modif import run
# from admin.users_suppr import run
# from admin.users import run
# from admin.vfs import run
# from admin.vfs_update import run
# from admin.virtualhost import run
# from admin.vcard import run
from admin.restapi import run